name: Build Jupyterlite and push it to build branch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push Jupyterlite
    env:
      BUILD_BRANCH: jupyterlite
      JUPYTERLITE_OUTPUT_DIR: jupyterlite/dist
      JUPYTERLITE_CONTENT_DIR: src/content/_jupyter
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Jupyterlite
        run: |
          cd jupyterlite
          mkdir ./files
          cp -r ${{ env.JUPYTERLITE_CONTENT_DIR }}/* ./files

          python -m pip install -r requirements.txt
          jupyter lite build --output-dir ${{ env.JUPYTERLITE_OUTPUT_DIR }}
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ${{ env.BUILD_BRANCH }}
          FOLDER: ${{ env.JUPYTERLITE_OUTPUT_DIR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
