name: Build Jupyterlite and push it to build branch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push Jupyterlite
    env:
      BUILD_BRANCH: jupyterlite
      BUILD_DIRECTORY: jupyterlite
      BUILD_OUTPUT_DIRECTORY: public
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Jupyterlite
        run: |
          cd ${{ env.BUILD_DIRECTORY }}
          mkdir ./files
          cp -r ../src/content/_jupyter/* ./files

          python -m pip install -r requirements.txt
          jupyter lite build --output-dir ${{ env.BUILD_OUTPUT_DIRECTORY }}

      - name: Apply custom patches
        env:
          PATCHES_DIRECTORY: patches
          TARGET_DIRECTORY: ${{ env.BUILD_OUTPUT_DIRECTORY }}
        run: |
          cd ${{ env.BUILD_DIRECTORY }}
          python patch.py

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ${{ env.BUILD_BRANCH }}
          FOLDER: ${{ env.BUILD_DIRECTORY }}/${{ env.BUILD_OUTPUT_DIRECTORY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
          TARGET_DIR: public
