name: Build and deploy Jupyterlite on Vercel via Deploy Hook after CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Jupyterlite and push to build branch
    env:
      BUILD_BRANCH: jupyterlite
      JUPYTERLITE_OUTPUT_DIR: dist
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Build Jupyterlite
        run: |
          cd jupyterlite
          sudo apt install wget
          wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba

          ./bin/micromamba shell init -s bash -p ~/micromamba
          source ~/.bashrc

          micromamba activate
          micromamba install python=3.10 -c conda-forge -y

          mkdir ./files
          cp -r ../src/content/_jupyter/* ./files

          python -m pip install -r requirements.txt
          jupyter lite build --output-dir ./${{ env.JUPYTERLITE_OUTPUT_DIR }}
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: ${{ env.BUILD_BRANCH }}
          FOLDER: ${{ env.JUPYTERLITE_OUTPUT_DIR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
