name: Code linting and typing check

on: [push]

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v1
      - name: Use Node.js 14 
        uses: actions/setup-node@v1
        with:
          node-version: 14 
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        - name: Install GitVersion
        uses: gittools/actions@v0.9.3
        with:
          versionSpec: 5.1.x
          includePrerelease: false
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9
      - name: Typecheck
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
