name: Deploy pre-built page to Vercel via Deplyo Hook

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install curl
        run: apt-get install curl
      - name: Use deploy hook
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_URL }}
