name: Code linting and typing check

on: [push]

jobs:
  lint-typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: NPM install
        run: npm i
      - name: Running TypeScript linter
        uses: icrawl/action-tsc@v1
  lint-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: NPM install
        run: npm i
      - name: Running ESLint (with autofix enabled)
        run: npx eslint . --fix
